### ISSUE TITLE
"Apollo Server supports only GET/POST requests."

### ISSUE THREAD

**Issue by chrishiste** [bencooling/serverless-plugin-graphiql#3]
Hello, first nice plugin but I can't make if work for some reason. GraphiQL runs on localhost but it says "Apollo Server supports only GET/POST requests." Any idea why ? THANKS 👍

**Comment by bencooling** [comment]
Hi @chrishiste Sorry I didn't see this issue until now. I'm not familiar with Apollo but it maybe also running on port 8000. You can change the port for this plugin, i.e. for port 3000 run the command `sls graphiql --port 3000`

**Comment by chrishiste** [comment]
I currently haven't time to check this out, I'll open a new issue if needed, thanks anyway 👍
